# Generated by Django 5.1.1 on 2024-11-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_user'),
        ('payments', '0002_payment_event_payment_qr_code_payment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.event'),
        ),
    ]
