# Generated by Django 5.1 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='https://storage.googleapis.com/{GS_BUCKET_NAME}/event_images/'),
        ),
    ]
