# Generated by Django 5.1 on 2024-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
